name: gitmodules pipeline
on:
 workflow_dispatch:
jobs:
 clone:
  runs-on: ubuntu-latest
  steps:
   - name: checkout repo
     uses: actions/checkout@v4
   - name: clone submodules
     run: |
      mkdir addons
      cd addons
      git submodule add https://github.com/dujanhung/extra-lua-preset
      git submodule add https://github.com/dujanhung/evtsbx-mod-lua-preset
   - name: create cache folder
     run: |
      cd .github
      mkdir cache
      cd cache
   - name: checkout upload artifact
     uses: actions/upload-artifact@v4
   - name: create zip file
     with:
      name: evtsbx-mod-template
      path: .github/cache
      