name: gitmodules pipeline
on:
 workflow_dispatch:
jobs:
 clone:
  runs-on: ubuntu-latest
  steps:
   - name: checkout repo
     uses: actions/checkout@v4
   - name: clone submodules
     run: |
      mkdir addons
      cd addons
      git submodule add https://github.com/dujanhung/extra-lua-preset
      git submodule add https://github.com/dujanhung/evtsbx-mod-lua-preset
      git submodule sync --recursive
   - name: commit
     run: |
      git config --local user.name "dujanhung"
      git config --local user.email "chanhung2008.duong@gmail.com"
      git commit -m "sync submodules"
      git push