name: nest repo
on:
 push:
  paths:
   - '.gitmodules'
jobs:
 update-submodule:
  runs-on: ubuntu-latest
  steps:
   - name: checkout main repo
     uses: actions/checkout@v4
     with:
      token: ${{ secrets.GITHUB_TOKEN }}
       submodules: true
   - name: update submodule
     run: git submodule update --remote --merge
   - name: commit updated submodule pointer
     run: |
      git config user.name "github-actions"
      git config user.email "github-actions@github.com"
      git add docs/external-repo
      git commit -m "update submodule" || echo "no changes"
      git push