name: pack repo
on:
 workflow_dispatch:
env:
 FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
jobs:
 pack-repo:
  runs-on: ubuntu-latest
  steps:
   - name: get checkout
     uses: actions/checkout@v5
   - name: add submodules
     run: |
      mkdir addons
      cd addons
      git submodule add https://github.com/dujanhung/extra-lua-preset
      git submodule add https://github.com/dujanhung/evtsbx-mod-lua-preset
      cd .
   - name: sanitize
     run: |
      rm .gitmodules *.md */.git
      find . -type f -name ".gitmodules" -exec rm {} \;
      rmdir .github/* */.github/* .git/* .gitmodules */.gitmodules
   - name: upload artifact
     uses: actions/upload-artifact@v6
     with:
      name: evtsbx-mod-template
      path: evtsbx-mod-template.zip
      compression-level: 9