name: pack repo
on:
 workflow_dispatch:
env:
 FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
 FOLDER_NAME: evtsbx-mod-template
jobs:
 pack-repo:
  runs-on: ubuntu-latest
  steps:
   - name: checkout repo
     uses: actions/checkout@v5
   - name: add submodules
     run: |
      cd .
      mkdir addons
      cd addons
      git submodule add https://github.com/dujanhung/extra-lua-preset
      git submodule add https://github.com/dujanhung/evtsbx-mod-lua-preset
      cd .
   - name: sanitize
     run: |
      find . -type f -name "*.md" -exec rm {} \;
      find . -type f -name ".gitmodules" -exec rm {} \;
      find . -type f -name ".git" -exec rm {} \;
      find . -type d -name "*/.github" -exec rmdir {} \;
      find . -type d -name "*/.git" -exec rmdir {} \;
   - name: move
     run: |
      cd .
      mkdir $FOLDER_NAME
      cd $FOLDER_NAME
      shopt -s dotglob nullglob
      for i in . ; do
       if $i==$FOLDER_NAME ; then
        continue
       fi
       mv -- $i $FOLDER_NAME
      cd .
   - name: upload artifact
     uses: actions/upload-artifact@v6
     with:
      name: evtsbx-mod-template
      path: .
      compression-level: 9