name: validate JSON
on:
 workflow_dispatch:
 pull-requests:
  - "*.json"
env:
 FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
jobs:
 validate-json:
  runs-on: ubuntu-latest
  steps:
   - name: get checkout
     uses: actions/checkout@v5
   - name: validate JSON
     run: |
      for file in *.json; do
       if jq empty "$file" >/dev/null 2>&1; then
        exit 0
       else
        exit 1
       fi