name: validate JSON
on:
 workflow_dispatch:
 pull_request:
  paths:
   - "**.json"
env:
 FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
 JSON_SCHEMA: .github/schema/info.json
 JSON_TARGET: info.json
jobs:
 validate-json:
  runs-on: ubuntu-latest
  steps:
   - name: checkout repo
     uses: actions/checkout@v5
   - name: schema syntax check
     run: |
      jq empty "$JSON_SCHEMA"
   - name: target syntax check
     run: |
      jq empty "$JSON_TARGET"
   - name: checkout json-schema-validator repo
     uses: actions/checkout@v5
     with:
      repository: dujanhung/json-schema-validator
      path: json-schema-validator
   - name: setup Python
     uses: actions/setup-python@v6
     with:
      python-version: '3.14'
   - name: schema check
     run: |
      python json-schema-validator/script.py "$JSON_SCHEMA" "$JSON_TARGET"