name: validate JSON
on:
 workflow_dispatch:
env:
 FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
jobs:
 validate-json:
  runs-on: ubuntu-latest
  steps:
   - name: checkout repo
     uses: actions/checkout@v5
   - name: schema syntax check
     run: |
      file=".github/schema/info.json"
      echo "open $file"
      jq empty "$file"
      echo "validated $file"
   - name: target syntax check
     run: |
      file="info.json"
      echo "open $file"
      jq empty "$file"
      echo "validated $file"
   - name: checkout json-validator repo
     uses: actions/checkout@v4
     with:
      repository: dujanhung/json-validator
      path: json-validator
   - name: setup Python
     uses: actions/setup-python@v5
     with:
      python-version: '3.14'
   - name: schema check
     run: |
      python json-validator/script.py .github/schema/info.json info.json